//views
const setupView = document.getElementById("setupView")
const activeView = document.getElementById("activeView")
const completedView = document.getElementById("completeView")
//buttons
const startBtn = document.getElementById("startBtn")
const stopBtn = document.getElementById("stopBtn")
const viewStatsBtn = document.getElementById("viewStatsBtn")
//form inputs (setup view)
const websiteUrl = document.getElementById("websiteUrl")
const startTime = document.getElementById("startTime")
const duration = document.getElementById("duration")
const totalDays = document.getElementById("totalDays")
//Display elements (active view)
const timer = document.getElementById("timer")
const streakNumber = document.getElementById("streakNumber")
const progress = document.getElementById("progressText")
const siteName = document.getElementById("siteName")
const progressFill = document.getElementById("progressFill")
